### PR TITLE
fix: use hash~..hash format for DiffViewOpen command in open_diff_view

### PR DESCRIPTION
**Pull request by sassanh**

### CODE REVIEW

**Comment by aaronhallaert** [comment]
Can you describe the difference or show an example of what's changing functionally?

**Comment by sassanh** [comment]
Sure, this is the reproduction steps of the bug I tried to fix:

1. Configure advanced-git-search to use diffview instead of fugitive
2. Type `:AdvancedGitSearch search_log_content<cr>` when working directory is in a git repository with some commits
3. Hit enter on an item

On my machine I get this error message:

```
   Error  20:36:01 msg_show.lua_error Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:187: The coroutine failed with this message: 
	context: cur_thread=main co_thread=<thread 0x0106d93230> co_func=...iffview.nvim/lua/diffview/scene/views/diff/diff_view.lua:327
.../share/nvim/lazy/diffview.nvim/lua/diffview/renderer.lua:166: attempt to get length of local 'text' (a function value)
stack traceback:
	.../share/nvim/lazy/diffview.nvim/lua/diffview/renderer.lua: in function 'add_text'
	...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:107: in function 'render_file_tree_recurse'
	...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:112: in function 'render_file_tree_recurse'
	...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:112: in function 'render_file_tree_recurse'
	...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:112: in function 'render_file_tree_recurse'
	...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:120: in function 'render_file_tree'
	...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:130: in function 'render_files'
	...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:176: in function <...y/diffview.nvim/lua/diffview/scene/views/diff/render.lua:134>
	...ffview.nvim/lua/diffview/scene/views/diff/file_panel.lua:400: in function 'render'
	...iffview.nvim/lua/diffview/scene/views/diff/diff_view.lua:465: in function 'func'
	...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:373: in function <...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:358>
stack traceback:
	[C]: in function 'error'
	...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:187: in function 'raise'
	...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:215: in function 'step'
	...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:247: in function 'notify_all'
	...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:222: in function 'step'
	...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:399: in function <...cal/share/nvim/lazy/diffview.nvim/lua/diffview/async.lua:391>
```

and diffview opens in a bad state.

I noticed advanced-git-search is trying to open diffview using `DiffView -uno <commit_hash> -- <file_name>` in `open_diff_view` and this is causing the error, I think what we are looking for is viewing the diff of that particular commit which, as you are already doing in `open_commit`, can be achieved by running diffview with `<commit_hash>^..<commit_hash>`.

So I tried to reuse that logic by putting it in a function and calling that function in `open_diff_view` and `open_commit`.

**Comment by aaronhallaert** [comment]
I appreciate your work trying to fix this issue!
However, I think there is a difference between the two implementations

Hitting `Enter` on an entry should show the difference between the commit and the current buffer.
`Ctrl-e` will open the commit itself.
If I understand correctly:
- `DiffviewOpen -uno commit`: diff the current state and a commit => `Enter`
- `DiffviewOpen -uno commit~..commit`: diff the selected commit and the one before (so just a diff of a specific commit) => `Ctrl-e`

If you think I'm wrong about this, can you share a minimal git repo (or some steps to reproduce this repo state) that triggers this error?
Also, some version numbers can be handy to track the issue:
- nvim
- diffview
- telescope/fzf

**Comment by sassanh** [comment]
Thanks for the explanation! ❤️

Diffview, when called with a single commit hash, raises an error on two of my repositories on more than 20 commits I tried it with. But I tried it in a fresh repository and it worked.

So, now that I understand diffview is actually supposed to be able to be called with a single commit and it doesn't necessarily need a commit range, I understand it is a feature in advanced-git-search and not a bug and I should track the issue in diffview.

**Pull request closed without merging**
